# Generated by Django 3.2.5 on 2021-07-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_doctor_specialization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientstoDoctors',
            new_name='PatientDoctor',
        ),
    ]
