# Generated by Django 3.2.5 on 2021-07-31 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_medications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medications',
            old_name='medicine',
            new_name='name',
        ),
        migrations.AddField(
            model_name='patientdoctor',
            name='medicine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='main_app.medications'),
        ),
    ]
