# Generated by Django 3.2.5 on 2021-07-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='office_location',
            field=models.CharField(max_length=500),
        ),
    ]
