# Generated by Django 3.2.5 on 2021-07-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_patientstodoctors_patientdoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
